services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "3002:3002"
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  db:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432"
  redis:
    image: redis:6.0.16-alpine
    ports:
      - "6379"
    volumes:
      - redis:/data
volumes:
  db:
  redis:
